---
language: python
sudo: false
cache: pip
matrix:
  allow_failures:
    - python: nightly
    - env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
  exclude:
    - python: "3.3"
      env: DJANGO="Django>=1.9,<1.10"
    - python: "3.3"
      env: DJANGO="https://github.com/django/django/archive/master.tar.gz"
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="https://github.com/django/django/archive/master.tar.gz"
before_install:
  - pip install -q codecov
install:
  - pip install -q $DJANGO
  - python setup.py -q install
script:
  - coverage run setup.py -v test
after_success:
  - codecov
